package io.github.prakharr0.ai.rca.spring.boot.core.model;

/**
 * Represents a single root cause hypothesis generated by the AI analysis engine.
 *
 * <p>Each {@code RootCause} is a ranked, structured hypothesis about why an exception
 * occurred. Hypotheses are purely diagnostic — no fixes or code changes are suggested.
 *
 * <p>Instances are returned as part of {@link AiRcaResponse#rootCauses()}, ordered
 * by {@link #rank} ascending (1 = most likely).
 *
 * @param rank                  The ordinal position of this hypothesis in the ranked list.
 *                              Starts at {@code 1} (most likely). Lower rank = higher likelihood.
 * @param title                 A short, human-readable label summarizing the suspected cause.
 *                              Example: {@code "Missing datasource configuration"}.
 * @param likelihood            A qualitative confidence level for this hypothesis.
 *                              Expected values: {@code "High"}, {@code "Medium"}, {@code "Low"}.
 * @param category              The domain or layer where the root cause is suspected.
 *                              Example: {@code "Configuration"}, {@code "Network"}, {@code "Database"}.
 * @param reasoning             A detailed explanation of why the AI suspects this cause,
 *                              based on the exception type, stack trace, and collected context.
 * @param diagnosticStep        A concrete, actionable step the developer can take to
 *                              isolate or confirm this hypothesis. Does not suggest a fix.
 *                              Example: {@code "Check spring.datasource.url in application.yml"}.
 * @param estimatedTimeToVerify A human-readable estimate of how long verification should take.
 *                              Example: {@code "< 5 minutes"}.
 *
 * @see AiRcaResponse
 */
public record RootCause(
        int rank,
        String title,
        String likelihood,
        String category,
        String reasoning,
        String diagnosticStep,
        String estimatedTimeToVerify
) {}
