package io.github.prakharr0.ai.rca.spring.boot.starter.config;

import org.springframework.boot.actuate.endpoint.annotation.*;
import org.springframework.stereotype.Component;
import io.github.prakharr0.ai.rca.spring.boot.core.analysis.impl.DefaultAiRcaAnalyzer;

import java.util.Map;

/**
 * Spring Boot Actuator endpoint exposing AI RCA diagnostic results.
 *
 * <p>
 * This endpoint allows retrieval of cached root cause analysis results
 * generated by the AI analyzer. It is useful for debugging and observability
 * without requiring direct access to application internals.
 *
 * <h2>Actuator Endpoint</h2>
 * <ul>
 *     <li>Endpoint ID: {@code ai-rca}</li>
 *     <li>Type: Read-only</li>
 *     <li>Visibility: Actuator management interface</li>
 * </ul>
 *
 * <h2>Security Considerations</h2>
 * Diagnostic results may contain sensitive failure context. It is recommended
 * to secure actuator endpoints in production environments.
 *
 * @see Endpoint
 */
@Component
@Endpoint(id = "ai-rca")
public class AiRcaEndpoint {

    /**
     * AI root cause analyzer used to retrieve cached results.
     */
    private final DefaultAiRcaAnalyzer analyzer;

    /**
     * Creates a new actuator endpoint backed by the provided analyzer.
     *
     * @param aiRcaAnalyzer AI analyzer instance (injected by Spring)
     */
    public AiRcaEndpoint(DefaultAiRcaAnalyzer aiRcaAnalyzer) {
        this.analyzer = aiRcaAnalyzer;
    }

    /**
     * Reads cached AI analysis results.
     *
     * <p>
     * The returned map contains fingerprint-to-analysis mappings generated
     * during previous exception handling operations.
     *
     * @return map of analysis results keyed by exception fingerprint
     */
    @ReadOperation
    public Map<String, ?> results() {
        return analyzer.getResults();
    }
}
