package io.github.prakharr0.ai.rca.spring.boot.core.context;

/**
 * Immutable snapshot of diagnostic context collected at the time an exception occurs.
 *
 * <p>
 * This record encapsulates all structured metadata required for AI-based
 * Root Cause Analysis (RCA). It is typically produced by {@link ContextCollector}
 * and consumed by components such as AI analyzers or prompt builders.
 *
 * <h2>Purpose</h2>
 * The snapshot aggregates:
 * <ul>
 *     <li>Exception metadata</li>
 *     <li>Stack trace details</li>
 *     <li>Recent application logs</li>
 *     <li>Runtime environment information</li>
 *     <li>Deployment and technology stack characteristics</li>
 * </ul>
 *
 * <h2>Immutability</h2>
 * Being a Java {@code record}, this class is:
 * <ul>
 *     <li>Immutable</li>
 *     <li>Thread-safe</li>
 *     <li>Value-based (auto-generated equals/hashCode/toString)</li>
 * </ul>
 *
 * <h2>Usage</h2>
 * Instances of this record are typically:
 * <ol>
 *     <li>Generated by {@link ContextCollector}</li>
 *     <li>Serialized into prompts for AI models</li>
 *     <li>Used for fingerprint generation</li>
 * </ol>
 *
 * @param exceptionType           fully qualified class name of the original thrown exception
 * @param rootCauseType           fully qualified class name of the deepest cause in the exception chain
 * @param rootCauseMessage        message of the root cause exception
 * @param stackTrace              truncated stack trace (typically top N frames of root cause)
 * @param recentLogs              recent application log buffer contents
 * @param springVersion           detected Spring Framework version
 * @param javaVersion             active Java runtime version
 * @param activeProfiles          active Spring profiles (defaults to "default" if not set)
 * @param packaging               application packaging type (e.g., "jar", "war")
 * @param deploymentEnvironment   inferred deployment target (e.g., "local", "kubernetes")
 * @param database                detected database stack (e.g., "jdbc", "none")
 * @param webStack                detected web stack (e.g., "spring-mvc", "webflux", "none")
 * @param buildTool               detected build tool (e.g., "maven", "gradle", "unknown")
 *
 * @see ContextCollector
 */
public record ContextSnapshot(
        String exceptionType,
        String rootCauseType,
        String rootCauseMessage,
        String stackTrace,
        String recentLogs,
        String springVersion,
        String javaVersion,
        String activeProfiles,
        String packaging,
        String deploymentEnvironment,
        String database,
        String webStack,
        String buildTool
) {}